name: Update latest issues

on:
  push:
  pull_request:

jobs:
  update-latest-issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - name: update issues
        id: updateIssues
        run: bash ./sources-for-download/script-for-using-latest-version.sh
      - name: config git
        run: |
          git config --local user.email "1439809+joergi@users.noreply.github.com"
          git config --local user.name "Joergi via GitHub Actions"
          git commit -am "update to use latest version"
      - name: Create Pull Request
        id: createAutoPR
        uses: peter-evans/create-pull-request@v4
        with:
          title: Automated Pull Request
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          body: Automated pull request created by GitHub Actions
          branch: automated_PR_for_update_issues
          branch-suffix: timestamp
          delete-branch: true
          labels: "automerge"
      - name: Auto approve
        id: autoApprove
        if: steps.createAutoPR.outputs.pull-request-operation == 'created'
        uses: juliangruber/approve-pull-request-action@v2
        with:
          github-token: ${{ secrets.MY_GITHUB_TOKEN }}
          number: ${{ steps.createAutoPR.outputs.pull-request-number }}
      - name: printnumber
        run: echo ${{ steps.autoApprove.NUMBER }}
      - name: Enable Pull Request Automerge
        if: steps.createAutoPR.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          pull-request-number: ${{ steps.createAutoPR.outputs.pull-request-number }}
